name: miinq_integrations
description: Shared integration clients and platform bridges for the MiinQ app monorepo.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ^3.7.2
  flutter: '>=3.24.0'

dependencies:
  collection: any
  convert: any
  crypto: any
  flutter:
    sdk: flutter
  http: any
  http_parser: any
  image: any
  json_annotation: any
  meta: any

dev_dependencies:
  build_runner: any
  flutter_test:
    sdk: flutter
  json_serializable: any
  test: any
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: false
