targets:
  $default:
    builders:
      isar_generator:
        generate_for:
          include:
            - lib/domain/**.dart
            - lib/data/local/models/**.dart
            - lib/core/sync/**.dart
          exclude:
            - lib/domain/pair/**.dart
