#!/bin/bash
sed -i 's/^  _fe_analyzer_shared: any/  _fe_analyzer_shared: ^61.0.0/' pubspec.yaml
sed -i 's/^  _flutterfire_internals: any/  _flutterfire_internals: ^1.3.59/' pubspec.yaml
sed -i 's/^  analyzer: any/  analyzer: ^5.13.0/' pubspec.yaml
sed -i 's/^  analyzer_plugin: any/  analyzer_plugin: ^0.11.2/' pubspec.yaml
sed -i 's/^  animations: any/  animations: ^2.0.11/' pubspec.yaml
sed -i 's/^  app_links: any/  app_links: ^6.4.1/' pubspec.yaml
sed -i 's/^  app_links_linux: any/  app_links_linux: ^1.0.3/' pubspec.yaml
sed -i 's/^  app_links_platform_interface: any/  app_links_platform_interface: ^2.0.2/' pubspec.yaml
sed -i 's/^  app_links_web: any/  app_links_web: ^1.0.4/' pubspec.yaml
sed -i 's/^  archive: any/  archive: ^4.0.7/' pubspec.yaml
sed -i 's/^  args: any/  args: ^2.7.0/' pubspec.yaml
sed -i 's/^  asn1lib: any/  asn1lib: ^1.6.5/' pubspec.yaml
sed -i 's/^  async: any/  async: ^2.12.0/' pubspec.yaml
sed -i 's/^  audio_session: any/  audio_session: ^0.2.2/' pubspec.yaml
sed -i 's/^  barcode: any/  barcode: ^2.2.9/' pubspec.yaml
sed -i 's/^  bidi: any/  bidi: ^2.0.13/' pubspec.yaml
sed -i 's/^  boolean_selector: any/  boolean_selector: ^2.1.2/' pubspec.yaml
sed -i 's/^  build: any/  build: ^2.4.1/' pubspec.yaml
sed -i 's/^  build_config: any/  build_config: ^1.1.2/' pubspec.yaml
sed -i 's/^  build_daemon: any/  build_daemon: ^4.0.4/' pubspec.yaml
sed -i 's/^  build_resolvers: any/  build_resolvers: ^2.4.2/' pubspec.yaml
sed -i 's/^  build_runner: any/  build_runner: ^2.4.13/' pubspec.yaml
sed -i 's/^  build_runner_core: any/  build_runner_core: ^7.3.2/' pubspec.yaml
sed -i 's/^  built_collection: any/  built_collection: ^5.1.1/' pubspec.yaml
sed -i 's/^  built_value: any/  built_value: ^8.12.0/' pubspec.yaml
sed -i 's/^  carp_serializable: any/  carp_serializable: ^2.0.1/' pubspec.yaml
sed -i 's/^  characters: any/  characters: ^1.4.0/' pubspec.yaml
sed -i 's/^  checked_yaml: any/  checked_yaml: ^2.0.3/' pubspec.yaml
sed -i 's/^  cli_util: any/  cli_util: ^0.3.5/' pubspec.yaml
sed -i 's/^  clock: any/  clock: ^1.1.2/' pubspec.yaml
sed -i 's/^  cloud_firestore: any/  cloud_firestore: ^5.6.12/' pubspec.yaml
sed -i 's/^  cloud_firestore_platform_interface: any/  cloud_firestore_platform_interface: ^6.6.12/' pubspec.yaml
sed -i 's/^  cloud_firestore_web: any/  cloud_firestore_web: ^4.4.12/' pubspec.yaml
sed -i 's/^  code_builder: any/  code_builder: ^4.11.0/' pubspec.yaml
sed -i 's/^  collection: any/  collection: ^1.19.1/' pubspec.yaml
sed -i 's/^  connectivity_plus: any/  connectivity_plus: ^7.0.0/' pubspec.yaml
sed -i 's/^  connectivity_plus_platform_interface: any/  connectivity_plus_platform_interface: ^2.0.1/' pubspec.yaml
sed -i 's/^  convert: any/  convert: ^3.1.2/' pubspec.yaml
sed -i 's/^  cross_file: any/  cross_file: ^0.3.4+2/' pubspec.yaml
sed -i 's/^  crypto: any/  crypto: ^3.0.6/' pubspec.yaml
sed -i 's/^  csv: any/  csv: ^6.0.0/' pubspec.yaml
sed -i 's/^  cupertino_icons: any/  cupertino_icons: ^1.0.8/' pubspec.yaml
sed -i 's/^  dart_style: any/  dart_style: ^2.3.2/' pubspec.yaml
sed -i 's/^  dartx: any/  dartx: ^1.2.0/' pubspec.yaml
sed -i 's/^  dbus: any/  dbus: ^0.7.11/' pubspec.yaml
sed -i 's/^  device_info_plus: any/  device_info_plus: ^12.1.0/' pubspec.yaml
sed -i 's/^  device_info_plus_platform_interface: any/  device_info_plus_platform_interface: ^7.0.3/' pubspec.yaml
sed -i 's/^  encrypt: any/  encrypt: ^5.0.3/' pubspec.yaml
sed -i 's/^  equatable: any/  equatable: ^2.0.7/' pubspec.yaml
sed -i 's/^  fake_async: any/  fake_async: ^1.3.3/' pubspec.yaml
sed -i 's/^  ffi: any/  ffi: ^2.1.4/' pubspec.yaml
sed -i 's/^  file: any/  file: ^7.0.1/' pubspec.yaml
sed -i 's/^  file_selector_linux: any/  file_selector_linux: ^0.9.3+2/' pubspec.yaml
sed -i 's/^  file_selector_macos: any/  file_selector_macos: ^0.9.4+4/' pubspec.yaml
sed -i 's/^  file_selector_platform_interface: any/  file_selector_platform_interface: ^2.6.2/' pubspec.yaml
sed -i 's/^  file_selector_windows: any/  file_selector_windows: ^0.9.3+4/' pubspec.yaml
sed -i 's/^  firebase_analytics: any/  firebase_analytics: ^11.6.0/' pubspec.yaml
sed -i 's/^  firebase_analytics_platform_interface: any/  firebase_analytics_platform_interface: ^4.4.3/' pubspec.yaml
sed -i 's/^  firebase_analytics_web: any/  firebase_analytics_web: ^0.5.10+16/' pubspec.yaml
sed -i 's/^  firebase_auth: any/  firebase_auth: ^5.7.0/' pubspec.yaml
sed -i 's/^  firebase_auth_platform_interface: any/  firebase_auth_platform_interface: ^7.7.3/' pubspec.yaml
sed -i 's/^  firebase_auth_web: any/  firebase_auth_web: ^5.15.3/' pubspec.yaml
sed -i 's/^  firebase_core: any/  firebase_core: ^3.15.2/' pubspec.yaml
sed -i 's/^  firebase_core_platform_interface: any/  firebase_core_platform_interface: ^6.0.1/' pubspec.yaml
sed -i 's/^  firebase_core_web: any/  firebase_core_web: ^2.24.1/' pubspec.yaml
sed -i 's/^  firebase_crashlytics: any/  firebase_crashlytics: ^4.3.10/' pubspec.yaml
sed -i 's/^  firebase_crashlytics_platform_interface: any/  firebase_crashlytics_platform_interface: ^3.8.10/' pubspec.yaml
sed -i 's/^  firebase_dynamic_links: any/  firebase_dynamic_links: ^6.1.10/' pubspec.yaml
sed -i 's/^  firebase_dynamic_links_platform_interface: any/  firebase_dynamic_links_platform_interface: ^0.2.7+10/' pubspec.yaml
sed -i 's/^  firebase_messaging: any/  firebase_messaging: ^15.2.10/' pubspec.yaml
sed -i 's/^  firebase_messaging_platform_interface: any/  firebase_messaging_platform_interface: ^4.6.10/' pubspec.yaml
sed -i 's/^  firebase_messaging_web: any/  firebase_messaging_web: ^3.10.10/' pubspec.yaml
sed -i 's/^  firebase_performance: any/  firebase_performance: ^0.10.1+10/' pubspec.yaml
sed -i 's/^  firebase_performance_platform_interface: any/  firebase_performance_platform_interface: ^0.1.5+10/' pubspec.yaml
sed -i 's/^  firebase_performance_web: any/  firebase_performance_web: ^0.1.7+16/' pubspec.yaml
sed -i 's/^  firebase_remote_config: any/  firebase_remote_config: ^5.5.0/' pubspec.yaml
sed -i 's/^  firebase_remote_config_platform_interface: any/  firebase_remote_config_platform_interface: ^2.0.0/' pubspec.yaml
sed -i 's/^  firebase_remote_config_web: any/  firebase_remote_config_web: ^1.8.9/' pubspec.yaml
sed -i 's/^  firebase_storage: any/  firebase_storage: ^12.4.10/' pubspec.yaml
sed -i 's/^  firebase_storage_platform_interface: any/  firebase_storage_platform_interface: ^5.2.10/' pubspec.yaml
sed -i 's/^  firebase_storage_web: any/  firebase_storage_web: ^3.10.17/' pubspec.yaml
sed -i 's/^  fixnum: any/  fixnum: ^1.1.1/' pubspec.yaml
sed -i 's/^  fl_chart: any/  fl_chart: ^1.1.1/' pubspec.yaml
sed -i 's/^  flutter: any/  flutter: ^0.0.0/' pubspec.yaml
sed -i 's/^  flutter_driver: any/  flutter_driver: ^0.0.0/' pubspec.yaml
sed -i 's/^  flutter_heatmap_calendar: any/  flutter_heatmap_calendar: ^1.0.5/' pubspec.yaml
sed -i 's/^  flutter_hooks: any/  flutter_hooks: ^0.21.2/' pubspec.yaml
sed -i 's/^  flutter_image_compress: any/  flutter_image_compress: ^2.4.0/' pubspec.yaml
sed -i 's/^  flutter_image_compress_common: any/  flutter_image_compress_common: ^1.0.6/' pubspec.yaml
sed -i 's/^  flutter_image_compress_macos: any/  flutter_image_compress_macos: ^1.0.3/' pubspec.yaml
sed -i 's/^  flutter_image_compress_ohos: any/  flutter_image_compress_ohos: ^0.0.3/' pubspec.yaml
sed -i 's/^  flutter_image_compress_platform_interface: any/  flutter_image_compress_platform_interface: ^1.0.5/' pubspec.yaml
sed -i 's/^  flutter_image_compress_web: any/  flutter_image_compress_web: ^0.1.5/' pubspec.yaml
sed -i 's/^  flutter_lints: any/  flutter_lints: ^5.0.0/' pubspec.yaml
sed -i 's/^  flutter_local_notifications: any/  flutter_local_notifications: ^19.4.2/' pubspec.yaml
sed -i 's/^  flutter_local_notifications_linux: any/  flutter_local_notifications_linux: ^6.0.0/' pubspec.yaml
sed -i 's/^  flutter_local_notifications_platform_interface: any/  flutter_local_notifications_platform_interface: ^9.1.0/' pubspec.yaml
sed -i 's/^  flutter_local_notifications_windows: any/  flutter_local_notifications_windows: ^1.0.3/' pubspec.yaml
sed -i 's/^  flutter_localizations: any/  flutter_localizations: ^0.0.0/' pubspec.yaml
sed -i 's/^  flutter_markdown: any/  flutter_markdown: ^0.7.7+1/' pubspec.yaml
sed -i 's/^  flutter_plugin_android_lifecycle: any/  flutter_plugin_android_lifecycle: ^2.0.30/' pubspec.yaml
sed -i 's/^  flutter_riverpod: any/  flutter_riverpod: ^2.6.1/' pubspec.yaml
sed -i 's/^  flutter_staggered_animations: any/  flutter_staggered_animations: ^1.1.1/' pubspec.yaml
sed -i 's/^  flutter_test: any/  flutter_test: ^0.0.0/' pubspec.yaml
sed -i 's/^  flutter_tts: any/  flutter_tts: ^4.2.3/' pubspec.yaml
sed -i 's/^  flutter_web_plugins: any/  flutter_web_plugins: ^0.0.0/' pubspec.yaml
sed -i 's/^  freezed: any/  freezed: ^2.5.2/' pubspec.yaml
sed -i 's/^  freezed_annotation: any/  freezed_annotation: ^2.4.4/' pubspec.yaml
sed -i 's/^  frontend_server_client: any/  frontend_server_client: ^4.0.0/' pubspec.yaml
sed -i 's/^  fuchsia_remote_debug_protocol: any/  fuchsia_remote_debug_protocol: ^0.0.0/' pubspec.yaml
sed -i 's/^  geolocator: any/  geolocator: ^14.0.1/' pubspec.yaml
sed -i 's/^  geolocator_android: any/  geolocator_android: ^5.0.2/' pubspec.yaml
sed -i 's/^  geolocator_apple: any/  geolocator_apple: ^2.3.13/' pubspec.yaml
sed -i 's/^  geolocator_platform_interface: any/  geolocator_platform_interface: ^4.2.6/' pubspec.yaml
sed -i 's/^  geolocator_web: any/  geolocator_web: ^4.1.3/' pubspec.yaml
sed -i 's/^  geolocator_windows: any/  geolocator_windows: ^0.2.5/' pubspec.yaml
sed -i 's/^  glob: any/  glob: ^2.1.3/' pubspec.yaml
sed -i 's/^  go_router: any/  go_router: ^16.2.4/' pubspec.yaml
sed -i 's/^  google_fonts: any/  google_fonts: ^6.3.2/' pubspec.yaml
sed -i 's/^  google_identity_services_web: any/  google_identity_services_web: ^0.3.3+1/' pubspec.yaml
sed -i 's/^  google_sign_in: any/  google_sign_in: ^7.2.0/' pubspec.yaml
sed -i 's/^  google_sign_in_android: any/  google_sign_in_android: ^7.2.0/' pubspec.yaml
sed -i 's/^  google_sign_in_ios: any/  google_sign_in_ios: ^6.2.1/' pubspec.yaml
sed -i 's/^  google_sign_in_platform_interface: any/  google_sign_in_platform_interface: ^3.1.0/' pubspec.yaml
sed -i 's/^  google_sign_in_web: any/  google_sign_in_web: ^1.1.0/' pubspec.yaml
sed -i 's/^  graphs: any/  graphs: ^2.3.2/' pubspec.yaml
sed -i 's/^  gtk: any/  gtk: ^2.1.0/' pubspec.yaml
sed -i 's/^  health: any/  health: ^13.2.1/' pubspec.yaml
sed -i 's/^  hooks_riverpod: any/  hooks_riverpod: ^2.6.1/' pubspec.yaml
sed -i 's/^  http: any/  http: ^1.5.0/' pubspec.yaml
sed -i 's/^  http_multi_server: any/  http_multi_server: ^3.2.2/' pubspec.yaml
sed -i 's/^  http_parser: any/  http_parser: ^4.1.2/' pubspec.yaml
sed -i 's/^  image: any/  image: ^4.5.4/' pubspec.yaml
sed -i 's/^  image_cropper: any/  image_cropper: ^11.0.0/' pubspec.yaml
sed -i 's/^  image_cropper_for_web: any/  image_cropper_for_web: ^7.0.0/' pubspec.yaml
sed -i 's/^  image_cropper_platform_interface: any/  image_cropper_platform_interface: ^8.0.0/' pubspec.yaml
sed -i 's/^  image_picker: any/  image_picker: ^1.2.0/' pubspec.yaml
sed -i 's/^  image_picker_android: any/  image_picker_android: ^0.8.13+1/' pubspec.yaml
sed -i 's/^  image_picker_for_web: any/  image_picker_for_web: ^3.1.0/' pubspec.yaml
sed -i 's/^  image_picker_ios: any/  image_picker_ios: ^0.8.13/' pubspec.yaml
sed -i 's/^  image_picker_linux: any/  image_picker_linux: ^0.2.2/' pubspec.yaml
sed -i 's/^  image_picker_macos: any/  image_picker_macos: ^0.2.2/' pubspec.yaml
sed -i 's/^  image_picker_platform_interface: any/  image_picker_platform_interface: ^2.11.0/' pubspec.yaml
sed -i 's/^  image_picker_windows: any/  image_picker_windows: ^0.2.2/' pubspec.yaml
sed -i 's/^  import_lint: any/  import_lint: ^1.0.1/' pubspec.yaml
sed -i 's/^  in_app_review: any/  in_app_review: ^2.0.11/' pubspec.yaml
sed -i 's/^  in_app_review_platform_interface: any/  in_app_review_platform_interface: ^2.0.5/' pubspec.yaml
sed -i 's/^  integration_test: any/  integration_test: ^0.0.0/' pubspec.yaml
sed -i 's/^  intl: any/  intl: ^0.20.2/' pubspec.yaml
sed -i 's/^  io: any/  io: ^1.0.5/' pubspec.yaml
sed -i 's/^  isar: any/  isar: ^3.1.0+1/' pubspec.yaml
sed -i 's/^  isar_flutter_libs: any/  isar_flutter_libs: ^3.1.0+1/' pubspec.yaml
sed -i 's/^  isar_generator: any/  isar_generator: ^3.1.0+1/' pubspec.yaml
sed -i 's/^  jni: any/  jni: ^0.14.2/' pubspec.yaml
sed -i 's/^  js: any/  js: ^0.6.7/' pubspec.yaml
sed -i 's/^  json_annotation: any/  json_annotation: ^4.9.0/' pubspec.yaml
sed -i 's/^  json_serializable: any/  json_serializable: ^6.8.0/' pubspec.yaml
sed -i 's/^  just_audio: any/  just_audio: ^0.10.5/' pubspec.yaml
sed -i 's/^  just_audio_platform_interface: any/  just_audio_platform_interface: ^4.6.0/' pubspec.yaml
sed -i 's/^  just_audio_web: any/  just_audio_web: ^0.4.16/' pubspec.yaml
sed -i 's/^  leak_tracker: any/  leak_tracker: ^11.0.2/' pubspec.yaml
sed -i 's/^  leak_tracker_flutter_testing: any/  leak_tracker_flutter_testing: ^3.0.10/' pubspec.yaml
sed -i 's/^  leak_tracker_testing: any/  leak_tracker_testing: ^3.0.2/' pubspec.yaml
sed -i 's/^  lints: any/  lints: ^5.1.1/' pubspec.yaml
sed -i 's/^  logger: any/  logger: ^2.6.1/' pubspec.yaml
sed -i 's/^  logging: any/  logging: ^1.3.0/' pubspec.yaml
sed -i 's/^  lottie: any/  lottie: ^3.3.2/' pubspec.yaml
sed -i 's/^  markdown: any/  markdown: ^7.3.0/' pubspec.yaml
sed -i 's/^  matcher: any/  matcher: ^0.12.17/' pubspec.yaml
sed -i 's/^  material_color_utilities: any/  material_color_utilities: ^0.11.1/' pubspec.yaml
sed -i 's/^  meta: any/  meta: ^1.17.0/' pubspec.yaml
sed -i 's/^  miinq_integrations: any/  miinq_integrations: ^0.1.0/' pubspec.yaml
sed -i 's/^  mime: any/  mime: ^2.0.0/' pubspec.yaml
sed -i 's/^  mocktail: any/  mocktail: ^1.0.4/' pubspec.yaml
sed -i 's/^  nm: any/  nm: ^0.5.0/' pubspec.yaml
sed -i 's/^  package_config: any/  package_config: ^2.2.0/' pubspec.yaml
sed -i 's/^  package_info_plus: any/  package_info_plus: ^9.0.0/' pubspec.yaml
sed -i 's/^  package_info_plus_platform_interface: any/  package_info_plus_platform_interface: ^3.2.1/' pubspec.yaml
sed -i 's/^  path: any/  path: ^1.9.1/' pubspec.yaml
sed -i 's/^  path_parsing: any/  path_parsing: ^1.1.0/' pubspec.yaml
sed -i 's/^  path_provider: any/  path_provider: ^2.1.5/' pubspec.yaml
sed -i 's/^  path_provider_android: any/  path_provider_android: ^2.2.18/' pubspec.yaml
sed -i 's/^  path_provider_foundation: any/  path_provider_foundation: ^2.4.2/' pubspec.yaml
sed -i 's/^  path_provider_linux: any/  path_provider_linux: ^2.2.1/' pubspec.yaml
sed -i 's/^  path_provider_platform_interface: any/  path_provider_platform_interface: ^2.1.2/' pubspec.yaml
sed -i 's/^  path_provider_windows: any/  path_provider_windows: ^2.3.0/' pubspec.yaml
sed -i 's/^  pdf: any/  pdf: ^3.11.3/' pubspec.yaml
sed -i 's/^  pdf_widget_wrapper: any/  pdf_widget_wrapper: ^1.0.4/' pubspec.yaml
sed -i 's/^  pedantic: any/  pedantic: ^1.11.1/' pubspec.yaml
sed -i 's/^  petitparser: any/  petitparser: ^6.1.0/' pubspec.yaml
sed -i 's/^  platform: any/  platform: ^3.1.6/' pubspec.yaml
sed -i 's/^  plugin_platform_interface: any/  plugin_platform_interface: ^2.1.8/' pubspec.yaml
sed -i 's/^  pointycastle: any/  pointycastle: ^3.9.1/' pubspec.yaml
sed -i 's/^  pool: any/  pool: ^1.5.2/' pubspec.yaml
sed -i 's/^  posix: any/  posix: ^6.0.3/' pubspec.yaml
sed -i 's/^  printing: any/  printing: ^5.14.2/' pubspec.yaml
sed -i 's/^  process: any/  process: ^5.0.3/' pubspec.yaml
sed -i 's/^  pub_semver: any/  pub_semver: ^2.2.0/' pubspec.yaml
sed -i 's/^  pubspec_parse: any/  pubspec_parse: ^1.5.0/' pubspec.yaml
sed -i 's/^  qr: any/  qr: ^3.0.2/' pubspec.yaml
sed -i 's/^  quick_actions: any/  quick_actions: ^1.1.0/' pubspec.yaml
sed -i 's/^  quick_actions_android: any/  quick_actions_android: ^1.0.23/' pubspec.yaml
sed -i 's/^  quick_actions_ios: any/  quick_actions_ios: ^1.2.1/' pubspec.yaml
sed -i 's/^  quick_actions_platform_interface: any/  quick_actions_platform_interface: ^1.1.0/' pubspec.yaml
sed -i 's/^  quiver: any/  quiver: ^3.2.2/' pubspec.yaml
sed -i 's/^  riverpod: any/  riverpod: ^2.6.1/' pubspec.yaml
sed -i 's/^  rxdart: any/  rxdart: ^0.28.0/' pubspec.yaml
sed -i 's/^  sentry: any/  sentry: ^9.6.0/' pubspec.yaml
sed -i 's/^  sentry_flutter: any/  sentry_flutter: ^9.6.0/' pubspec.yaml
sed -i 's/^  share_plus: any/  share_plus: ^12.0.0/' pubspec.yaml
sed -i 's/^  share_plus_platform_interface: any/  share_plus_platform_interface: ^6.1.0/' pubspec.yaml
sed -i 's/^  shared_preferences: any/  shared_preferences: ^2.5.3/' pubspec.yaml
sed -i 's/^  shared_preferences_android: any/  shared_preferences_android: ^2.4.13/' pubspec.yaml
sed -i 's/^  shared_preferences_foundation: any/  shared_preferences_foundation: ^2.5.4/' pubspec.yaml
sed -i 's/^  shared_preferences_linux: any/  shared_preferences_linux: ^2.4.1/' pubspec.yaml
sed -i 's/^  shared_preferences_platform_interface: any/  shared_preferences_platform_interface: ^2.4.1/' pubspec.yaml
sed -i 's/^  shared_preferences_web: any/  shared_preferences_web: ^2.4.3/' pubspec.yaml
sed -i 's/^  shared_preferences_windows: any/  shared_preferences_windows: ^2.4.1/' pubspec.yaml
sed -i 's/^  shelf: any/  shelf: ^1.4.2/' pubspec.yaml
sed -i 's/^  shelf_web_socket: any/  shelf_web_socket: ^2.0.1/' pubspec.yaml
sed -i 's/^  sky_engine: any/  sky_engine: ^0.0.0/' pubspec.yaml
sed -i 's/^  source_gen: any/  source_gen: ^1.5.0/' pubspec.yaml
sed -i 's/^  source_helper: any/  source_helper: ^1.3.5/' pubspec.yaml
sed -i 's/^  source_span: any/  source_span: ^1.10.1/' pubspec.yaml
sed -i 's/^  speech_to_text: any/  speech_to_text: ^7.3.0/' pubspec.yaml
sed -i 's/^  speech_to_text_platform_interface: any/  speech_to_text_platform_interface: ^2.3.0/' pubspec.yaml
sed -i 's/^  speech_to_text_windows: any/  speech_to_text_windows: ^1.0.0+beta.8/' pubspec.yaml
sed -i 's/^  sprintf: any/  sprintf: ^7.0.0/' pubspec.yaml
sed -i 's/^  stack_trace: any/  stack_trace: ^1.12.1/' pubspec.yaml
sed -i 's/^  state_notifier: any/  state_notifier: ^1.0.0/' pubspec.yaml
sed -i 's/^  stream_channel: any/  stream_channel: ^2.1.4/' pubspec.yaml
sed -i 's/^  stream_transform: any/  stream_transform: ^2.1.1/' pubspec.yaml
sed -i 's/^  string_scanner: any/  string_scanner: ^1.4.1/' pubspec.yaml
sed -i 's/^  sync_http: any/  sync_http: ^0.3.1/' pubspec.yaml
sed -i 's/^  synchronized: any/  synchronized: ^3.3.1/' pubspec.yaml
sed -i 's/^  term_glyph: any/  term_glyph: ^1.2.2/' pubspec.yaml
sed -i 's/^  test_api: any/  test_api: ^0.7.7/' pubspec.yaml
sed -i 's/^  tflite_flutter: any/  tflite_flutter: ^0.11.0/' pubspec.yaml
sed -i 's/^  time: any/  time: ^2.1.5/' pubspec.yaml
sed -i 's/^  timezone: any/  timezone: ^0.10.1/' pubspec.yaml
sed -i 's/^  timing: any/  timing: ^1.0.2/' pubspec.yaml
sed -i 's/^  typed_data: any/  typed_data: ^1.4.0/' pubspec.yaml
sed -i 's/^  url_launcher: any/  url_launcher: ^6.3.2/' pubspec.yaml
sed -i 's/^  url_launcher_android: any/  url_launcher_android: ^6.3.20/' pubspec.yaml
sed -i 's/^  url_launcher_ios: any/  url_launcher_ios: ^6.3.4/' pubspec.yaml
sed -i 's/^  url_launcher_linux: any/  url_launcher_linux: ^3.2.1/' pubspec.yaml
sed -i 's/^  url_launcher_macos: any/  url_launcher_macos: ^3.2.3/' pubspec.yaml
sed -i 's/^  url_launcher_platform_interface: any/  url_launcher_platform_interface: ^2.3.2/' pubspec.yaml
sed -i 's/^  url_launcher_web: any/  url_launcher_web: ^2.4.1/' pubspec.yaml
sed -i 's/^  url_launcher_windows: any/  url_launcher_windows: ^3.1.4/' pubspec.yaml
sed -i 's/^  uuid: any/  uuid: ^4.5.1/' pubspec.yaml
sed -i 's/^  vector_math: any/  vector_math: ^2.2.0/' pubspec.yaml
sed -i 's/^  very_good_analysis: any/  very_good_analysis: ^6.0.0/' pubspec.yaml
sed -i 's/^  vm_service: any/  vm_service: ^14.3.1/' pubspec.yaml
sed -i 's/^  watcher: any/  watcher: ^1.1.3/' pubspec.yaml
sed -i 's/^  web: any/  web: ^1.1.1/' pubspec.yaml
sed -i 's/^  web_socket: any/  web_socket: ^1.0.1/' pubspec.yaml
sed -i 's/^  web_socket_channel: any/  web_socket_channel: ^3.0.3/' pubspec.yaml
sed -i 's/^  webdriver: any/  webdriver: ^3.0.4/' pubspec.yaml
sed -i 's/^  win32: any/  win32: ^5.13.0/' pubspec.yaml
sed -i 's/^  win32_registry: any/  win32_registry: ^2.1.0/' pubspec.yaml
sed -i 's/^  workmanager: any/  workmanager: ^0.7.0/' pubspec.yaml
sed -i 's/^  xdg_directories: any/  xdg_directories: ^1.1.0/' pubspec.yaml
sed -i 's/^  xml: any/  xml: ^6.5.0/' pubspec.yaml
sed -i 's/^  xxh3: any/  xxh3: ^1.2.0/' pubspec.yaml
sed -i 's/^  yaml: any/  yaml: ^3.1.3/' pubspec.yaml
