name: Generate API Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Generate API documentation
        run: bash tool/generate_api_docs.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-docs
          path: |
            build/api_docs
            api-docs.tar.gz
